version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_Strong_Password!
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - crud_network
  webapp:
    image: vampcv/crudapp:latest
    ports:
        - "5000:8080"
    depends_on:
        - sqlserver
    networks:
        - crud_network


volumes:
  sql_data:

networks:
  crud_network:
