apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: vampcv/crudapp:latest
          ports:
            - containerPort: 8080
