name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Execute o workflow apenas no push para a branch `main`
  pull_request:  # Também executa em pull requests para validação
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configuração do Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t vampcv/crudapp:latest .

       # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      # Teste local (opcional)
      - name: Test Docker Image (Optional)
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml down

      # Push da imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push vampcv/crudapp:latest
